// If you modify this list, please keep the labels in metrics.c in sync.
enum {
    METRIC_DNS_CACHE_INSERTED,
    METRIC_DNS_CACHE_LIVE_FREED,
    METRIC_DNS_QUERIES_FORWARDED,
    METRIC_DNS_AUTH_ANSWERED,
    METRIC_DNS_LOCAL_ANSWERED,
    METRIC_BOOTP,
    METRIC_PXE,
    METRIC_DHCPACK,
    METRIC_DHCPDECLINE,
    METRIC_DHCPDISCOVER,
    METRIC_DHCPINFORM,
    METRIC_DHCPNAK,
    METRIC_DHCPOFFER,
    METRIC_DHCPRELEASE,
    METRIC_DHCPREQUEST,
    METRIC_NOANSWER,
    METRIC_LEASES_ALLOCATED_4,
    METRIC_LEASES_PRUNED_4,
    METRIC_LEASES_ALLOCATED_6,
    METRIC_LEASES_PRUNED_6,

    __METRIC_MAX,
};

const char* get_metric_name(int);
